### ISSUE TITLE
Ignore certain files?

### ISSUE THREAD

**Issue by Jakobud** [MaartenDesnouck/google-apps-script#108] opened 2018-04-27 21:48 UTC
Is it possible to ignore certain files? So when you do a blanket `gas push` it doesn't upload certain files? Sort of like a gitignore but for gas? Cause otherwise Google Apps Scripts returns errors for unsupported file types.

For example if you have some other things in your directory like a package.json or some Node.js scripts for compiling SASS > CSS, etc... Any of that stuff gas tries to upload it when you `gas push` and then it throws errors.

**Comment by MaartenDesnouck** [comment] 2018-08-01 13:35
Duplicate of #69

**Closed by MaartenDesnouck** 2018-08-01 13:35 UTC
